# Generated by Django 4.0.5 on 2022-11-17 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='img/')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroFinanciero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoCuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='TipoRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidad', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, unique=True)),
                ('clave', models.TextField()),
                ('icono', models.ImageField(blank=True, default='', upload_to='img/')),
                ('codigo', models.CharField(max_length=60)),
                ('minimarket', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='miniApi.usuario')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='miniApi.tipocuenta')),
            ],
        ),
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=60)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miniApi.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.IntegerField()),
                ('registroFinanciero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miniApi.registrofinanciero')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miniApi.unidad')),
            ],
        ),
        migrations.AddField(
            model_name='registrofinanciero',
            name='minimarket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miniApi.usuario'),
        ),
        migrations.AddField(
            model_name='registrofinanciero',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='miniApi.tiporegistro'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='minimarket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miniApi.usuario'),
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('stock', models.FloatField()),
                ('precio', models.PositiveIntegerField()),
                ('nVentas', models.PositiveBigIntegerField()),
                ('img', models.ImageField(blank=True, default='', upload_to='img/')),
                ('categorias', models.ManyToManyField(blank=True, default='', to='miniApi.categoria')),
                ('minimarket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miniApi.usuario')),
                ('proveedor', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='miniApi.proveedor')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='miniApi.unidad')),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miniApi.proveedor')),
            ],
        ),
        migrations.AddField(
            model_name='categoria',
            name='minimarket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='miniApi.usuario'),
        ),
    ]
