# Generated by Django 4.0.5 on 2022-11-12 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miniApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categorias',
            field=models.ManyToManyField(blank=True, default='', to='miniApi.categoria'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='img',
            field=models.ImageField(blank=True, default='', upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='proveedor',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.DO_NOTHING, to='miniApi.proveedor'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='icono',
            field=models.ImageField(blank=True, default='', upload_to='img/'),
        ),
    ]
