# Generated by Django 4.0.5 on 2022-10-12 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
